// <auto-generated />
namespace ProjectManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mmmmm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mmmmm));
        
        string IMigrationMetadata.Id
        {
            get { return "201603112131403_mmmmm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
